name: Deploy CDK Stack

on:
  push:
    paths:
      - 'app.py'
      - 'stacks/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mycdkproject -f .github/Dockerfile .

      - name: Run Docker container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          docker run --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY mycdkproject /bin/bash -c "set -e; echo 'Starting setup.sh'; /opt/app/.github/setup.sh; echo 'setup.sh completed successfully'"
